# versionは3系が最新版で、versionによって書き方が異なる
version: "3"
services:
  mysql:
    build: ./mysql/    #Dockerfileからビルドすることを示す
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    image: mysql_server # イメージの名前
    environment:
      - MYSQL_ROOT_PASSWORD=puari123#   #コンテナ内のMySQLを起動する際のパスワードを設定
      - COMPOSE_HTTP_TIMEOUT=1000
    ports:
      - "3306:3306"